### ISSUE TITLE
"Show midi note name in tooltip" FR: Also show named notename

### ISSUE THREAD

**Issue by Phroneris** [nofishonfriday/ReaScripts#2]
"Named notename" would be a strange expression though...

Currently the tooltip tells pitch name like `C4` and beat position like `1.0.0`.
I mean it would be nice if the script additionaly indicates note names that are defined by loading note name files or by double right clicking on the left keyboard.

Considering the name of the script, it would be more natural for it to behave this way.

**Comment by nofishonfriday** [comment]
@Phroneris Sorry for late reply, this is now in v1.02 (update in ReaPack).
